### PR TITLE
fix: Update the color of the transparency overlay in the jogging panel to match the background

### PR DESCRIPTION
**Pull request by sn3ek**
This change fixes the background color of the transparency overlay.

### CODE REVIEW

**Comment by evrys** [comment]
You can probably just change the defaults in the TransparentOverlay component since those are the two places it's used

**Comment by vgerber** [comment]
@evrys  Is there a reason the overlay needs to have a color?

**Comment by sn3ek** [comment]
> @evrys Is there a reason the overlay needs to have a color?
Since the transparencyoverlay has a default color I need to override it. I can indeed check if "none" also works.

**Comment by sn3ek** [comment]
With and without color
Bildschirmfoto 2024-09-20 um 09 35 19
Bildschirmfoto 2024-09-20 um 09 35 26

**Comment by bompo** [comment]
Does it work for the "light" theme as well? IMO it should use a mui theme color?

**Comment by evrys** [comment]
No particular reason for it to have a color, TransparentOverlay component was just a quick hacky workaround from me so feel free to tweak it 🙂

**Pull request merged**
